export const UPDATE_NAV = 'UPDATE_NAV';
export const FIELD_INVALID = 'FIELD_INVALID';
export const FIELD_AUTHOR = 'FIELD_AUTHOR';
export const FIELD_TITLE = 'FIELD_TITLE';
export const FIELD_BODY = 'FIELD_BODY';

export const GET_POSTS = 'GET_POSTS';
export const GET_POSTS_PENDING = 'GET_POSTS_PENDING';
export const GET_POSTS_FULFILLED = 'GET_POSTS_FULFILLED';

export const INIT_IMGS = 'INIT_IMGS';

export const GET_IMGS = 'GET_IMGS';
export const GET_IMGS_PENDING = 'GET_IMGS_PENDING';
export const GET_IMGS_FULFILLED = 'GET_IMGS_FULFILLED';

export const GET_SINGLE_POST = 'GET_SINGLE_POST';
export const GET_SINGLE_POST_PENDING = 'GET_SINGLE_POST_PENDING';
export const GET_SINGLE_POST_FULFILLED = 'GET_SINGLE_POST_FULFILLED';

export const GET_UPDATE_POST = 'GET_UPDATE_POST';
export const GET_UPDATE_POST_PENDING = 'GET_UPDATE_POST_PENDING';
export const GET_UPDATE_POST_FULFILLED = 'GET_UPDATE_POST_FULFILLED';

export const GET_DELETE_POST = 'GET_DELETE_POST';
export const GET_DELETE_POST_PENDING = 'GET_DELETE_POST_PENDING';
export const GET_DELETE_POST_FULFILLED = 'GET_DELETE_POST_FULFILLED';

export const GET_CREATE_POST = 'GET_CREATE_POST';
export const GET_CREATE_POST_PENDING = 'GET_CREATE_POST_PENDING';
export const GET_CREATE_POST_FULFILLED = 'GET_CREATE_POST_FULFILLED';
